import {
  Lead,
  Customer,
  Vehicle,
  Employee,
  Task,
  Message,
  AIAuditLog,
  Campaign,
  PipelineStage,
  ParkReason,
  LostReason,
} from '@/types/crm';
import { AcquisitionStateMachine } from '../engine/state-machine';
import { ValuationEngine } from '../engine/valuation';
import { SLATaskEngine } from '../engine/sla-tasks';

// Initial Employees
export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 'emp_01',
    name: 'Karthi Selvan',
    email: 'karthi.s@vikaalam.com',
    phone: '+91 98840 12345',
    role: 'SALES_MANAGER',
    branch: 'Chennai - Anna Nagar',
    location: 'Chennai',
    languages: ['Tamil', 'English'],
    skills: ['Superbikes', 'High-Value Deals', 'Escalation Resolver'],
    activeLeadsCount: 14,
    pendingTasksCount: 3,
    maxLeadCapacity: 35,
    performanceRating: 4.9,
    conversionRate: 14.8,
    status: 'ONLINE',
  },
  {
    id: 'emp_02',
    name: 'Priya Sundaram',
    email: 'priya.s@vikaalam.com',
    phone: '+91 98401 67890',
    role: 'SALES_EXECUTIVE',
    branch: 'Chennai - Velachery',
    location: 'Chennai',
    languages: ['Tamil', 'English', 'Telugu'],
    skills: ['Fast-Closer', 'Scooters & Commuters', 'Instant Valuation'],
    activeLeadsCount: 18,
    pendingTasksCount: 5,
    maxLeadCapacity: 30,
    performanceRating: 4.7,
    conversionRate: 11.4,
    status: 'ONLINE',
  },
  {
    id: 'emp_03',
    name: 'Vignesh Rao',
    email: 'vignesh.r@vikaalam.com',
    phone: '+91 99002 34567',
    role: 'SALES_EXECUTIVE',
    branch: 'Bangalore - Indiranagar',
    location: 'Bangalore',
    languages: ['Kannada', 'English', 'Hindi'],
    skills: ['High-Value', 'Negotiation Expert'],
    activeLeadsCount: 12,
    pendingTasksCount: 4,
    maxLeadCapacity: 28,
    performanceRating: 4.6,
    conversionRate: 10.2,
    status: 'ONLINE',
  },
  {
    id: 'emp_04',
    name: 'Ramesh Kumar',
    email: 'ramesh.k@vikaalam.com',
    phone: '+91 97910 88990',
    role: 'INSPECTOR',
    branch: 'Chennai - Central Hub',
    location: 'Chennai',
    languages: ['Tamil', 'English'],
    skills: ['Engine Diagnostics', 'Chassis Alignment', '15-Min Quick Check'],
    activeLeadsCount: 6,
    pendingTasksCount: 2,
    maxLeadCapacity: 12,
    performanceRating: 4.8,
    conversionRate: 88.0,
    status: 'ONLINE',
  },
  {
    id: 'emp_05',
    name: 'Suresh Babu',
    email: 'suresh.b@vikaalam.com',
    phone: '+91 98450 11223',
    role: 'INSPECTOR',
    branch: 'Bangalore - Koramangala Hub',
    location: 'Bangalore',
    languages: ['Kannada', 'English', 'Tamil'],
    skills: ['Odometer Tamper Detection', 'Electrical Diagnostics'],
    activeLeadsCount: 5,
    pendingTasksCount: 1,
    maxLeadCapacity: 12,
    performanceRating: 4.9,
    conversionRate: 91.5,
    status: 'ONLINE',
  },
  {
    id: 'emp_06',
    name: 'Divya Menon',
    email: 'divya.m@vikaalam.com',
    phone: '+91 98845 99887',
    role: 'MARKETING_MANAGER',
    branch: 'Chennai - Corporate HQ',
    location: 'Chennai',
    languages: ['English', 'Tamil', 'Malayalam'],
    skills: ['Reactivation Campaigns', 'Meta Ads ROI', 'WhatsApp Flow Optimization'],
    activeLeadsCount: 0,
    pendingTasksCount: 2,
    maxLeadCapacity: 10,
    performanceRating: 4.8,
    conversionRate: 8.5,
    status: 'ONLINE',
  },
];

// Initial Production Seed Leads
export const INITIAL_LEADS: Lead[] = [
  {
    id: 'L10291',
    customerId: 'C1001',
    customer: {
      id: 'C1001',
      name: 'Anand Natarajan',
      phone: '+91 98402 11223',
      whatsapp: '+91 98402 11223',
      email: 'anand.natarajan@gmail.com',
      city: 'Chennai',
      preferredLanguage: 'Tamil',
      totalLeadsCount: 1,
      totalPurchasedCount: 0,
      lifetimeValue: 0,
      createdAt: '2026-09-10T10:00:00Z',
    },
    vehicle: {
      id: 'V1001',
      leadId: 'L10291',
      brand: 'Honda',
      model: 'Activa 6G',
      variant: 'DLX Disc',
      year: 2022,
      registrationNumber: 'TN 09 BX 4412',
      registrationYear: 2022,
      kmRidden: 28000,
      fuelType: 'PETROL',
      ownerCount: 1,
      loanStatus: 'NONE',
      serviceHistory: 'COMPLETE_SHOWROOM',
      accidentHistory: 'NONE',
      customerExpectedPrice: 75000,
      documents: [
        { name: 'RC', label: 'Registration Certificate', status: 'VERIFIED', verifiedAt: '2026-09-10T10:30:00Z' },
        { name: 'INSURANCE', label: 'Insurance Policy', status: 'VERIFIED', verifiedAt: '2026-09-10T10:32:00Z' },
        { name: 'PUC', label: 'Pollution Under Control', status: 'VERIFIED', verifiedAt: '2026-09-10T10:35:00Z' },
        { name: 'OWNER_ID', label: 'Aadhaar / ID', status: 'VERIFIED', verifiedAt: '2026-09-10T10:35:00Z' },
      ],
      photos: [
        { angle: 'FRONT', label: 'Front View', status: 'VERIFIED' },
        { angle: 'REAR', label: 'Rear & Number Plate', status: 'VERIFIED' },
        { angle: 'LEFT', label: 'Left Side', status: 'VERIFIED' },
        { angle: 'RIGHT', label: 'Right Side', status: 'VERIFIED' },
        { angle: 'ODOMETER', label: 'Odometer (28,000 km)', status: 'VERIFIED' },
        { angle: 'ENGINE', label: 'Engine Bay', status: 'VERIFIED' },
        { angle: 'TYRES', label: 'Tyre Tread', status: 'VERIFIED' },
        { angle: 'RC_PHOTO', label: 'RC Smart Card', status: 'VERIFIED' },
      ],
    },
    valuation: {
      id: 'val_1001',
      vehicleId: 'V1001',
      baselineMarketValue: 78000,
      recommendedBuyMin: 68000,
      recommendedBuyMax: 71000,
      maxApprovedPrice: 73000,
      expectedResalePrice: 82000,
      expectedGrossMargin: 11000,
      confidenceScore: 92,
      reasoning: [
        'Single owner with complete showroom service records in Chennai',
        '28,000 km odometer verified with clear digital cluster',
        'Zero accidental claims; tyres possess 70% remaining tread life',
      ],
      calculatedAt: '2026-09-10T10:40:00Z',
    },
    quote: {
      id: 'quote_1001',
      leadId: 'L10291',
      initialOfferedPrice: 70000,
      currentOfferedPrice: 70000,
      customerCounterPrice: 75000,
      status: 'COUNTERED',
      version: 1,
      sentAt: '2026-09-10T11:00:00Z',
    },
    currentStage: '09_NEGOTIATION',
    previousStage: '08_QUOTE_SENT',
    source: 'WHATSAPP',
    assignedEmployeeId: 'emp_02',
    assignedEmployee: INITIAL_EMPLOYEES[1],
    qualificationStatus: 'QUALIFIED',
    leadScore: 88,
    leadTemperature: 'HOT',
    slaDueDate: new Date(Date.now() + 12 * 60 * 1000).toISOString(),
    isSlaBreached: false,
    conversionProbability: 74,
    lastCustomerMessageAt: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
    reactivationCount: 0,
    createdAt: '2026-09-10T10:00:00Z',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'L10292',
    customerId: 'C1002',
    customer: {
      id: 'C1002',
      name: 'Vikram Sundaram',
      phone: '+91 99001 99881',
      whatsapp: '+91 99001 99881',
      city: 'Bangalore',
      preferredLanguage: 'English',
      totalLeadsCount: 1,
      totalPurchasedCount: 0,
      lifetimeValue: 0,
      createdAt: '2026-09-11T08:30:00Z',
    },
    vehicle: {
      id: 'V1002',
      leadId: 'L10292',
      brand: 'Royal Enfield',
      model: 'Classic 350',
      variant: 'Signals Desert Sand',
      year: 2021,
      registrationNumber: 'KA 03 HM 7821',
      registrationYear: 2021,
      kmRidden: 19000,
      fuelType: 'PETROL',
      ownerCount: 1,
      loanStatus: 'NONE',
      serviceHistory: 'COMPLETE_SHOWROOM',
      accidentHistory: 'NONE',
      customerExpectedPrice: 155000,
      documents: [
        { name: 'RC', label: 'Registration Certificate', status: 'VERIFIED' },
        { name: 'INSURANCE', label: 'Comprehensive Insurance', status: 'VERIFIED' },
        { name: 'PUC', label: 'Pollution Certificate', status: 'VERIFIED' },
        { name: 'OWNER_ID', label: 'PAN Card', status: 'VERIFIED' },
      ],
      photos: [
        { angle: 'FRONT', label: 'Front Dual ABS', status: 'VERIFIED' },
        { angle: 'REAR', label: 'Rear Spoke', status: 'VERIFIED' },
        { angle: 'LEFT', label: 'Left Engine Guard', status: 'VERIFIED' },
        { angle: 'RIGHT', label: 'Right Silencer', status: 'VERIFIED' },
        { angle: 'ODOMETER', label: 'Odometer (19,000 km)', status: 'VERIFIED' },
        { angle: 'ENGINE', label: 'J-Series Engine', status: 'VERIFIED' },
      ],
    },
    valuation: {
      id: 'val_1002',
      vehicleId: 'V1002',
      baselineMarketValue: 165000,
      recommendedBuyMin: 145000,
      recommendedBuyMax: 150000,
      maxApprovedPrice: 154000,
      expectedResalePrice: 172000,
      expectedGrossMargin: 22000,
      confidenceScore: 94,
      reasoning: [
        'High market liquidity for Classic 350 Signals series in Bangalore',
        'Low mileage 19,000 km with pristine engine acoustics',
      ],
      calculatedAt: '2026-09-11T09:00:00Z',
    },
    quote: {
      id: 'quote_1002',
      leadId: 'L10292',
      initialOfferedPrice: 148000,
      currentOfferedPrice: 148000,
      status: 'ACCEPTED',
      version: 1,
      sentAt: '2026-09-11T09:15:00Z',
    },
    currentStage: '10_INSPECTION_PENDING',
    source: 'META_ADS',
    assignedEmployeeId: 'emp_03',
    assignedEmployee: INITIAL_EMPLOYEES[2],
    qualificationStatus: 'QUALIFIED',
    leadScore: 94,
    leadTemperature: 'HOT',
    slaDueDate: new Date(Date.now() + 25 * 60 * 1000).toISOString(),
    isSlaBreached: false,
    conversionProbability: 86,
    lastCustomerMessageAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    reactivationCount: 0,
    createdAt: '2026-09-11T08:30:00Z',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'L10293',
    customerId: 'C1003',
    customer: {
      id: 'C1003',
      name: 'Karthik Raja',
      phone: '+91 94432 44556',
      whatsapp: '+91 94432 44556',
      city: 'Coimbatore',
      preferredLanguage: 'Tamil',
      totalLeadsCount: 1,
      totalPurchasedCount: 0,
      lifetimeValue: 0,
      createdAt: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
    },
    vehicle: {
      id: 'V1003',
      leadId: 'L10293',
      brand: 'Yamaha',
      model: 'MT-15',
      variant: 'Version 2.0 Metallic Black',
      year: 2023,
      kmRidden: 14000,
      fuelType: 'PETROL',
      ownerCount: 1,
      loanStatus: 'NONE',
      serviceHistory: 'COMPLETE_SHOWROOM',
      accidentHistory: 'NONE',
      customerExpectedPrice: 135000,
      documents: [{ name: 'RC', label: 'RC', status: 'PENDING_VERIFICATION' }],
      photos: [],
    },
    currentStage: '01_NEW_LEAD',
    source: 'WHATSAPP',
    assignedEmployeeId: 'emp_02',
    assignedEmployee: INITIAL_EMPLOYEES[1],
    qualificationStatus: 'QUALIFIED',
    leadScore: 82,
    leadTemperature: 'HOT',
    slaDueDate: new Date(Date.now() + 3 * 60 * 1000).toISOString(),
    isSlaBreached: false,
    conversionProbability: 78,
    lastCustomerMessageAt: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
    reactivationCount: 0,
    createdAt: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'L10294',
    customerId: 'C1004',
    customer: {
      id: 'C1004',
      name: 'Murugan Chettiar',
      phone: '+91 98410 77665',
      whatsapp: '+91 98410 77665',
      city: 'Chennai',
      preferredLanguage: 'Tamil',
      totalLeadsCount: 1,
      totalPurchasedCount: 0,
      lifetimeValue: 0,
      createdAt: '2026-09-08T12:00:00Z',
    },
    vehicle: {
      id: 'V1004',
      leadId: 'L10294',
      brand: 'TVS',
      model: 'Jupiter',
      variant: 'ZX SmartXonnect',
      year: 2022,
      kmRidden: 22000,
      fuelType: 'PETROL',
      ownerCount: 1,
      loanStatus: 'NONE',
      serviceHistory: 'COMPLETE_SHOWROOM',
      accidentHistory: 'NONE',
      customerExpectedPrice: 66000,
      documents: [{ name: 'RC', label: 'RC', status: 'VERIFIED' }],
      photos: [],
    },
    valuation: {
      id: 'val_1004',
      vehicleId: 'V1004',
      baselineMarketValue: 62000,
      recommendedBuyMin: 54000,
      recommendedBuyMax: 57000,
      maxApprovedPrice: 59000,
      expectedResalePrice: 65000,
      expectedGrossMargin: 8000,
      confidenceScore: 88,
      reasoning: ['Customer wanted ₹66,000 against max market buy of ₹57,000'],
      calculatedAt: '2026-09-08T13:00:00Z',
    },
    quote: {
      id: 'quote_1004',
      leadId: 'L10294',
      initialOfferedPrice: 56000,
      currentOfferedPrice: 57000,
      customerCounterPrice: 66000,
      status: 'REJECTED',
      version: 2,
    },
    currentStage: 'PARKED',
    previousStage: '08_QUOTE_SENT',
    parkQueue: 'QUOTE_PARK',
    parkReason: 'PRICE_OBJECTION',
    parkedAt: '2026-09-08T14:00:00Z',
    reactivationDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    reactivationCount: 1,
    source: 'WEBSITE',
    assignedEmployeeId: 'emp_02',
    assignedEmployee: INITIAL_EMPLOYEES[1],
    qualificationStatus: 'QUALIFIED',
    leadScore: 68,
    leadTemperature: 'WARM',
    isSlaBreached: false,
    conversionProbability: 52,
    createdAt: '2026-09-08T12:00:00Z',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'L10295',
    customerId: 'C1005',
    customer: {
      id: 'C1005',
      name: 'Sameer Pasha',
      phone: '+91 97400 33445',
      whatsapp: '+91 97400 33445',
      city: 'Bangalore',
      preferredLanguage: 'English',
      totalLeadsCount: 1,
      totalPurchasedCount: 0,
      lifetimeValue: 0,
      createdAt: '2026-09-11T14:00:00Z',
    },
    vehicle: {
      id: 'V1005',
      leadId: 'L10295',
      brand: 'KTM',
      model: 'Duke 200',
      variant: 'BS6 Electronic Orange',
      year: 2020,
      registrationNumber: 'KA 01 EK 9012',
      registrationYear: 2020,
      kmRidden: 31000,
      fuelType: 'PETROL',
      ownerCount: 2,
      loanStatus: 'NONE',
      serviceHistory: 'PARTIAL',
      accidentHistory: 'MINOR_SCRATCHES',
      customerExpectedPrice: 125000,
      documents: [
        { name: 'RC', label: 'RC Card', status: 'VERIFIED' },
        { name: 'INSURANCE', label: 'Third Party', status: 'VERIFIED' },
      ],
      photos: [{ angle: 'FRONT', label: 'Front Angle', status: 'VERIFIED' }],
    },
    valuation: {
      id: 'val_1005',
      vehicleId: 'V1005',
      baselineMarketValue: 130000,
      recommendedBuyMin: 112000,
      recommendedBuyMax: 118000,
      maxApprovedPrice: 122000,
      expectedResalePrice: 138000,
      expectedGrossMargin: 20000,
      confidenceScore: 85,
      reasoning: ['Second owner vehicle with minor fairing scratches'],
      calculatedAt: '2026-09-11T14:30:00Z',
    },
    quote: {
      id: 'quote_1005',
      leadId: 'L10295',
      initialOfferedPrice: 118000,
      currentOfferedPrice: 118000,
      status: 'ACCEPTED',
      version: 1,
    },
    inspection: {
      id: 'insp_1005',
      leadId: 'L10295',
      vehicleId: 'V1005',
      inspectorId: 'emp_05',
      inspectorName: 'Suresh Babu',
      scheduledAt: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
      locationAddress: 'No. 44, 5th Cross, 100ft Road, Indiranagar, Bangalore',
      status: 'SCHEDULED',
      checklist: [],
      totalRepairDeduction: 0,
    },
    currentStage: '11_INSPECTION_SCHEDULED',
    source: 'INSTAGRAM',
    assignedEmployeeId: 'emp_03',
    assignedEmployee: INITIAL_EMPLOYEES[2],
    qualificationStatus: 'QUALIFIED',
    leadScore: 76,
    leadTemperature: 'WARM',
    isSlaBreached: false,
    conversionProbability: 82,
    createdAt: '2026-09-11T14:00:00Z',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'L10296',
    customerId: 'C1006',
    customer: {
      id: 'C1006',
      name: 'Manoj Kumar',
      phone: '+91 98844 55667',
      whatsapp: '+91 98844 55667',
      city: 'Chennai',
      preferredLanguage: 'Tamil',
      totalLeadsCount: 1,
      totalPurchasedCount: 0,
      lifetimeValue: 0,
      createdAt: '2026-09-11T11:00:00Z',
    },
    vehicle: {
      id: 'V1006',
      leadId: 'L10296',
      brand: 'Bajaj',
      model: 'Pulsar NS200',
      variant: 'Dual Channel ABS',
      year: 2021,
      registrationNumber: 'TN 07 DC 3390',
      registrationYear: 2021,
      kmRidden: 26000,
      fuelType: 'PETROL',
      ownerCount: 1,
      loanStatus: 'NONE',
      serviceHistory: 'COMPLETE_SHOWROOM',
      accidentHistory: 'NONE',
      customerExpectedPrice: 88000,
      documents: [
        { name: 'RC', label: 'RC', status: 'VERIFIED' },
        { name: 'INSURANCE', label: 'Insurance', status: 'VERIFIED' },
        { name: 'PUC', label: 'PUC', status: 'VERIFIED' },
      ],
      photos: [],
    },
    valuation: {
      id: 'val_1006',
      vehicleId: 'V1006',
      baselineMarketValue: 92000,
      recommendedBuyMin: 80000,
      recommendedBuyMax: 84000,
      maxApprovedPrice: 86000,
      expectedResalePrice: 98000,
      expectedGrossMargin: 14000,
      confidenceScore: 92,
      reasoning: ['First owner, verified showroom history'],
      calculatedAt: '2026-09-11T11:30:00Z',
    },
    quote: {
      id: 'quote_1006',
      leadId: 'L10296',
      initialOfferedPrice: 84000,
      currentOfferedPrice: 84000,
      status: 'ACCEPTED',
      version: 1,
    },
    inspection: {
      id: 'insp_1006',
      leadId: 'L10296',
      vehicleId: 'V1006',
      inspectorId: 'emp_04',
      inspectorName: 'Ramesh Kumar',
      scheduledAt: '2026-09-12T08:00:00Z',
      locationAddress: 'Plot 12, 3rd Avenue, Anna Nagar, Chennai',
      status: 'COMPLETED',
      totalRepairDeduction: 2500,
      finalRecommendedBuyPrice: 81500,
      outcome: 'BUY',
      completedAt: '2026-09-12T08:45:00Z',
      inspectorNotes: 'Engine block and transmission in excellent state. Front brake pads worn (deducted ₹1,000); rear tyre nearing 20% tread (deducted ₹1,500). Customer agreed to ₹81,500.',
      checklist: [
        { category: 'ENGINE', label: 'Engine Compression & Sound', status: 'PASS', repairEstimatedCost: 0 },
        { category: 'TRANSMISSION', label: 'Clutch & Gear Shift', status: 'PASS', repairEstimatedCost: 0 },
        { category: 'BRAKES', label: 'Front Disc Pads', status: 'MINOR_DEFECT', notes: 'Worn out pads', repairEstimatedCost: 1000 },
        { category: 'TYRES', label: 'Rear Tyre Tread', status: 'MINOR_DEFECT', notes: '25% life left', repairEstimatedCost: 1500 },
        { category: 'CHASSIS_FRAME', label: 'Chassis Alignment & Rust', status: 'PASS', repairEstimatedCost: 0 },
        { category: 'ELECTRICAL', label: 'Starter, Battery & Lights', status: 'PASS', repairEstimatedCost: 0 },
        { category: 'ODOMETER_TAMPERING', label: 'ECU vs Cluster Sync', status: 'PASS', repairEstimatedCost: 0 },
        { category: 'ROAD_TEST', label: 'High-speed Stability & Braking', status: 'PASS', repairEstimatedCost: 0 },
      ],
    },
    currentStage: '13_PURCHASE_APPROVAL',
    source: 'FACEBOOK',
    assignedEmployeeId: 'emp_01',
    assignedEmployee: INITIAL_EMPLOYEES[0],
    qualificationStatus: 'QUALIFIED',
    leadScore: 92,
    leadTemperature: 'HOT',
    slaDueDate: new Date(Date.now() + 45 * 60 * 1000).toISOString(),
    isSlaBreached: false,
    conversionProbability: 95,
    createdAt: '2026-09-11T11:00:00Z',
    updatedAt: new Date().toISOString(),
  },
];

// Initial Messages for Lead L10291 (The active negotiation showcase)
export const INITIAL_MESSAGES: Record<string, Message[]> = {
  L10291: [
    {
      id: 'msg_1',
      conversationId: 'L10291',
      sender: 'CUSTOMER',
      content: 'Vanakkam, I want to sell my 2022 Honda Activa 6G. It has run 28000 kms.',
      timestamp: '2026-09-10T10:01:00Z',
      status: 'READ',
    },
    {
      id: 'msg_2',
      conversationId: 'L10291',
      sender: 'AI_AGENT',
      agentName: 'Intake Agent',
      content:
        'Vanakkam Anand! We will gladly help you get the highest guaranteed price for your 2022 Honda Activa.\n\nAre you the 1st single owner, and is your RC card & insurance currently valid?',
      quickReplies: ['1st Single Owner', '2nd Owner', 'Insurance Active', 'RC Available'],
      timestamp: '2026-09-10T10:01:15Z',
      status: 'READ',
    },
    {
      id: 'msg_3',
      conversationId: 'L10291',
      sender: 'CUSTOMER',
      content: 'Yes, 1st owner, single hand use in Anna Nagar. All papers and insurance active.',
      timestamp: '2026-09-10T10:05:00Z',
      status: 'READ',
    },
    {
      id: 'msg_4',
      conversationId: 'L10291',
      sender: 'AI_AGENT',
      agentName: 'Valuation & Quote Agent',
      content:
        '✨ **VIKALAAM Certified Instant Valuation**\n\n🛵 **Vehicle**: Honda Activa 6G (2022)\n📊 **Market Fair Value**: ₹78,000\n💰 **Guaranteed Instant Buy Offer**: **₹70,000**\n\n✅ Free doorstep 15-min inspection\n✅ Instant bank account transfer on spot\n✅ Guaranteed 100% RC name transfer liability coverage\n\nPlease select an option below to proceed:',
      quickReplies: ['[ INTERESTED ]', '[ WANT TO DISCUSS ]', '[ NOT INTERESTED ]'],
      timestamp: '2026-09-10T10:05:40Z',
      status: 'READ',
    },
    {
      id: 'msg_5',
      conversationId: 'L10291',
      sender: 'CUSTOMER',
      content: 'Can you increase to ₹75,000? I took good care of the bike with only showroom service.',
      timestamp: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
      status: 'READ',
    },
  ],
};

// Initial Marketing Campaigns
export const INITIAL_CAMPAIGNS: Campaign[] = [
  {
    id: 'camp_01',
    name: 'Chennai Diwali Used-Bike Cash Rush',
    channel: 'META_ADS',
    targetSegment: 'Chennai Scooter & Commuter Sellers',
    targetCount: 1500,
    sentCount: 1420,
    responseCount: 384,
    qualifiedCount: 242,
    purchasesCount: 48,
    totalSpend: 42000,
    netGrossProfit: 528000,
    status: 'ACTIVE',
    createdAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'camp_02',
    name: 'Bangalore Royal Enfield Upgrade Drive',
    channel: 'WHATSAPP',
    targetSegment: 'Parked Leads - Price Objections (RE 350/500)',
    targetCount: 320,
    sentCount: 312,
    responseCount: 114,
    qualifiedCount: 78,
    purchasesCount: 19,
    totalSpend: 12500,
    netGrossProfit: 342000,
    status: 'ACTIVE',
    createdAt: '2026-09-05T00:00:00Z',
  },
  {
    id: 'camp_03',
    name: 'Smart Reactivation Engine - 7 Day Park Queue',
    channel: 'WHATSAPP',
    targetSegment: 'Automated Park Queue Unpark Trigger',
    targetCount: 680,
    sentCount: 645,
    responseCount: 228,
    qualifiedCount: 160,
    purchasesCount: 34,
    totalSpend: 8400,
    netGrossProfit: 374000,
    status: 'ACTIVE',
    createdAt: '2026-09-08T00:00:00Z',
  },
];
